import { ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Printer } from "lucide-react";
import { GhostButton, PrimaryButton } from "@/components/ui";
import { fmtDate } from "@/lib/format";
import { BRAND } from "@/lib/brand";

export interface ReportOrg {
  name: string;
  address: string | null;
  contact: string | null;
  license_no: string | null;
  logo_url: string | null;
}

/** Print-styled sheet shell shared by all MIS reports: toolbar (hidden in print),
 * centre header, title + date range, then arbitrary report body. */
export function ReportSheet({
  org,
  title,
  from,
  to,
  children,
  backTo = "/reports/mis",
  maxWidth = "max-w-[1100px]",
}: {
  org: ReportOrg;
  title: string;
  from: string;
  to: string;
  children: ReactNode;
  backTo?: string;
  maxWidth?: string;
}) {
  const navigate = useNavigate();
  const rangeLabel = `${fmtDate(from, "dd/MM/yy")} - ${fmtDate(to, "dd/MM/yy")}`;

  return (
    <div className="space-y-5">
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #report-sheet, #report-sheet * { visibility: visible !important; }
          #report-sheet { position: absolute; left: 0; top: 0; width: 100%; box-shadow: none !important; border: none !important; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <GhostButton onClick={() => navigate(backTo)} className="!py-2 !px-4">
          <ArrowLeft size={16} /> Back to MIS Reports
        </GhostButton>
        <PrimaryButton onClick={() => window.print()} className="!py-2 !px-4">
          <Printer size={16} /> Print / Save PDF
        </PrimaryButton>
      </div>

      <div id="report-sheet" className={`mx-auto ${maxWidth} rounded-card2 border border-line-card bg-card p-8 shadow-card sm:p-10`}>
        <div className="flex flex-wrap items-start justify-between gap-6 border-b border-line-table pb-5">
          <div className="flex items-start gap-4">
            {org.logo_url && <img src={org.logo_url} alt="" className="h-16 w-16 flex-shrink-0 object-contain" />}
            <div>
              <h1 className="font-display text-xl font-extrabold uppercase leading-tight text-accent sm:text-2xl">{org.name}</h1>
              {org.address && <p className="mt-1 text-[13px] font-semibold uppercase text-ink-3">{org.address}</p>}
              <p className="mt-0.5 text-[13px] font-semibold text-ink-3">
                {org.contact && <>Contact No. {org.contact}</>}
                {org.contact && org.license_no && " | "}
                {org.license_no && <>Lic No. - {org.license_no}</>}
              </p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-[13px] font-bold text-accent">{rangeLabel}</p>
            <h2 className="mt-1 font-display text-xl font-extrabold text-ink sm:text-2xl">{title}</h2>
          </div>
        </div>

        {children}

        <p className="mt-8 border-t border-line-table pt-4 text-center text-xs text-muted">
          Generated by {BRAND} · This is a computer-generated report.
        </p>
      </div>
    </div>
  );
}
